### ISSUE TITLE
DesignOps Day Hamburg (Fr Nov 19?)

### ISSUE THREAD

**Issue by filtercake** [DesignOps/discussion#5]
I do not want to organize an official conference or anything at this point or found another meetup.

[XP Days Germany 2016](http://www.xpdays.de/2016/) are in Hamburg from Nov 20 to 22., so let's just informally and unofficially meet on Saturday, Nov 19, in Hamburg.

I'm sure all the rest (location, wifi, coffee) will come together until then – and if not, we can still occupy some coffeeshop :)

**Comment by HerrBertling** [comment]
Cool! Also, there will be a decodeHH meetup all about (living) design systems which should discuss a *lot* of our topics :) http://www.meetup.com/decode-hh/events/230167276/
