### ISSUE TITLE
Talk at upfront Berlin 

### ISSUE THREAD

**Issue by filtercake** [DesignOps/discussion#8]
was asked to submit to [up.front](http://up.front.ug/). here is the proposal I sent (following the [submit guidelines](http://up.front.ug/submit/)), will share other stuff on the talk in this issue.

@kaelig all input is very welcome! would love to know what you would put in a talk.

Note: I like the idea of not creating DesignOps meetups, but only going to existing meetups :)

---

"DesignOps connects design goals with engineering requirements by providing culture, conventions and tools". Well, there a are probably a million other insufficient ways to express its scope in tweet-llength, but more importantly: DesignOps a thing now and we need your help to shape it and define it!

In his talk, Fabian will share the Why™ of DesignOps and where it could go. Maybe he can even get you excited to join the expedition...

**Comment by kaelig** [comment]
That's a really good start. I also like the idea of not creating DesignOps meetups for now.

Subject:

- what is the issue
- what are the potential remedies
- a few tools, methods and measures
- say something "you might be a design op already"
- drop mic

**Comment by filtercake** [comment]
@kaelig thx! will also steal some stuff from [Bridging the gap between designers and developers at the Guardian](http://www.slideshare.net/kaelig/bridging-the-gap-between-designers-and-developers-at-the-guardian) :)

since I am somewhat messy with using issues for notes, I will collect them at [designops @ upfront ug · Issue #2 · filtercake/talks](https://github.com/filtercake/talks/issues/2) and then post relevant here once it all makes sense...
